/**
 * Generated by scripts/build-card-art.mjs — do not edit by hand.
 *
 * Every photograph on a game card, with the licence it came under and who made
 * it. The credits page renders this; CC-BY and CC-BY-SA both require the
 * attribution to be shown, so it has to live somewhere a reader can reach.
 *
 * MANUAL CORRECTION — the six `logo` entries.
 * The generator copies Commons' `LicenseShortName` and nothing else, which for
 * these six reads "Public domain" and stops there. That is true of the
 * copyright and silent about the rest: all six are tagged PD-textlogo (a plain
 * wordmark, below the threshold of originality) *and* carry Commons'
 * `Restrictions: trademarked`. Stating only "Public domain" reads as a blanket
 * free-to-use claim over a registered trademark, so the licence strings were
 * widened by hand to say both. If `scripts/build-card-art.mjs` is ever re-run,
 * teach it to read `extmetadata.Restrictions` first or this is lost again.
 *
 * These entries cover the launcher card art only. Photographs shown during play
 * are credited at the point of use — see `ImageCredit` in `src/games/stages.tsx`
 * and `creditFor` in `src/content/wikipedia.ts`.
 */
export type ArtCredit = { subject: string; licence: string; author: string; file: string | null };

export const ART_CREDITS: Record<string, ArtCredit[]> = {
  "animal": [
    {
      "subject": "Red panda",
      "licence": "CC BY-SA 4.0",
      "author": "Sunuwargr",
      "file": "File:Red_Panda,_Gentle_Tree-Dweller_of_the_Himalayas.jpg"
    }
  ],
  "bird": [
    {
      "subject": "Atlantic puffin",
      "licence": "CC BY-SA 4.0",
      "author": "Charles J. Sharp",
      "file": "File:Puffin_(Fratercula_arctica).jpg"
    }
  ],
  "insect": [
    {
      "subject": "Monarch butterfly",
      "licence": "GFDL 1.2",
      "author": "Photo by and (c)2007 Derek Ramsey (Ram-Man)",
      "file": "File:Monarch_Butterfly_Danaus_plexippus_Male_2664px.jpg"
    }
  ],
  "plant": [
    {
      "subject": "Monstera deliciosa",
      "licence": "CC BY-SA 3.0",
      "author": "Wikimedia Commons",
      "file": "File:Monstera_deliciosa2.jpg"
    }
  ],
  "dish": [
    {
      "subject": "Paella",
      "licence": "CC BY-SA 4.0",
      "author": "Jan Harenburg",
      "file": "File:01_Paella_Valenciana_original.jpg"
    }
  ],
  "recipe": [
    {
      "subject": "Mise en place",
      "licence": "CC BY-SA 2.0",
      "author": "Charles Haynes",
      "file": "File:Mise_en_place_for_hot_station.jpg"
    }
  ],
  "landmark": [
    {
      "subject": "Machu Picchu",
      "licence": "CC BY-SA 4.0",
      "author": "Draceane",
      "file": "File:Machu_Picchu,_2023_(012).jpg"
    }
  ],
  "capital": [
    {
      "subject": "Prague",
      "licence": "CC BY 2.0",
      "author": "Moyan Brenn from Italy",
      "file": "File:Prague_(6365119737).jpg"
    }
  ],
  "skyline": [
    {
      "subject": "Manhattan",
      "licence": "CC BY-SA 4.0",
      "author": "Dllu",
      "file": "File:View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_(cropped).jpg"
    }
  ],
  "country": [
    {
      "subject": "Great Ocean Road",
      "licence": "CC BY 3.0",
      "author": "Bobak Ha'Eri",
      "file": "File:2009-0825-GreatOceanRoadsign.jpg"
    }
  ],
  "car": [
    {
      "subject": "Porsche 911",
      "licence": "CC BY-SA 4.0",
      "author": "Matti Blume",
      "file": "File:Porsche_911_No_1000000,_70_Years_Porsche_Sports_Car,_Berlin_(1X7A3888).jpg"
    }
  ],
  "sport": [
    {
      "subject": "Basketball",
      "licence": "CC BY 2.0",
      "author": "Erik Drost",
      "file": "File:Steph_Curry_(51915116957).jpg"
    }
  ],
  "boardgame": [
    {
      "subject": "Chess",
      "licence": "CC BY-SA 3.0",
      "author": "Alan Light",
      "file": "File:ChessSet.jpg"
    }
  ],
  "object": [
    {
      "subject": "Typewriter",
      "licence": "CC BY-SA 4.0",
      "author": "GodeNehler",
      "file": "File:MEK_II-371.jpg"
    }
  ],
  "word": [
    {
      "subject": "Scrabble",
      "licence": "CC BY 2.0",
      "author": "thebarrowboy",
      "file": "File:Scrabble_game_in_progress.jpg"
    }
  ],
  "outline": [
    {
      "subject": "World map",
      "licence": "Public domain",
      "author": "Tom Patterson",
      "file": "File:Equal-Earth-Physical-No-Type_(cropped).jpg"
    }
  ],
  "videogame": [
    {
      "subject": "Game controller",
      "licence": "Public domain",
      "author": "Evan-Amos",
      "file": "File:SNES-Controller-in-Hand.jpg"
    }
  ],
  "scene": [
    {
      "subject": "Kino Atlas Interier J",
      "licence": "CC0",
      "author": "Mojmir Churavy",
      "file": "File:Kino Atlas Interier J.jpg"
    }
  ],
  "year": [
    {
      "subject": "Marquee (structure)",
      "licence": "Public domain",
      "author": "William P. Gottlieb",
      "file": "File:View_of_the_Apollo_Theatre_marquee,_New_York,_N.Y.,_between_1946_and_1948_(William_P._Gottlieb_00141).jpg"
    }
  ],
  "rebus": [
    {
      "subject": "Emoji",
      "licence": "OFL",
      "author": "Google",
      "file": "File:Popular_Emoji_Groups_Noto_Color_Emoji.svg"
    }
  ],
  "logo": [
    {
      "subject": "Coca-Cola logo",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "The Coca-Cola Company",
      "file": "File:Coca-Cola logo.svg"
    },
    {
      "subject": "Logo NIKE",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "Carolyn Davidson, Nike",
      "file": "File:Logo NIKE.svg"
    },
    {
      "subject": "IBM logo",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "Paul Rand",
      "file": "File:IBM logo.svg"
    },
    {
      "subject": "McDonald's Golden Arches",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "McDonald's",
      "file": "File:McDonald's Golden Arches.svg"
    },
    {
      "subject": "Adidas Logo",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "Adidas",
      "file": "File:Adidas Logo.svg"
    },
    {
      "subject": "LEGO logo",
      "licence": "Public domain (PD-textlogo); trademarked",
      "author": "The Lego Group",
      "file": "File:LEGO logo.svg"
    }
  ],
  "celebrity": [
    {
      "subject": "Keanu Reeves",
      "licence": "CC BY-SA 4.0",
      "author": "Gabriel Hutchinson",
      "file": "File:Keanu_Reeves_at_TIFF_2025_02_(Cropped).jpg"
    },
    {
      "subject": "Zendaya",
      "licence": "CC BY-SA 4.0",
      "author": "PhilipRomano",
      "file": "File:Zendaya-byPhilipRomano.jpg"
    },
    {
      "subject": "Idris Elba",
      "licence": "CC BY-SA 4.0",
      "author": "Bryan Berlin",
      "file": "File:Idris_Elba_A_House_of_Dynamite-21_(cropped).jpg"
    },
    {
      "subject": "Emma Stone",
      "licence": "CC BY-SA 4.0",
      "author": "Harald Krichel",
      "file": "File:Emma_Stone_at_the_2025_Venice_Film_Festival-6313_(cropped).jpg"
    },
    {
      "subject": "Pedro Pascal",
      "licence": "CC BY-SA 4.0",
      "author": "Gabriel Hutchinson",
      "file": "File:Pedro_Pascal_at_the_2025_Cannes_Film_Festival_04.jpg"
    },
    {
      "subject": "Viola Davis",
      "licence": "CC BY-SA 4.0",
      "author": "Nomoretitanic",
      "file": "File:Viola_Davis_at_the_Air_Premiere_at_SXSW_(cropped).jpg"
    }
  ],
  "quote": [
    {
      "subject": "Albert Einstein",
      "licence": "Public domain",
      "author": "Oren Jack Turner",
      "file": "File:Albert_Einstein_Head_cleaned.jpg"
    },
    {
      "subject": "Mark Twain",
      "licence": "Public domain",
      "author": "A.F. Bradley, New York",
      "file": "File:Mark_Twain_by_AF_Bradley_(cropped_2).jpg"
    },
    {
      "subject": "Winston Churchill",
      "licence": "Public domain",
      "author": "Yousuf Karsh",
      "file": "File:Sir_Winston_Churchill_-_19086236948_(restored).jpg"
    },
    {
      "subject": "Maya Angelou",
      "licence": "Public domain",
      "author": "Clinton Library",
      "file": "File:Angelou_at_Clinton_inauguration_(cropped_2).jpg"
    },
    {
      "subject": "Nelson Mandela",
      "licence": "CC BY-SA 2.0",
      "author": "Kingkongphoto &amp; www.celebrity-photos.com from Laurel",
      "file": "File:Nelson_Mandela_1994.jpg"
    },
    {
      "subject": "Marie Curie",
      "licence": "Public domain",
      "author": "Henri Manuel",
      "file": "File:Marie_Curie_c._1920s.jpg"
    }
  ],
  "app": [
    {
      "subject": "Spotify: Music and Podcasts",
      "licence": "App Store artwork",
      "author": "Spotify",
      "file": null
    },
    {
      "subject": "Duolingo: Language Lessons",
      "licence": "App Store artwork",
      "author": "Duolingo",
      "file": null
    },
    {
      "subject": "Airbnb",
      "licence": "App Store artwork",
      "author": "Airbnb, Inc.",
      "file": null
    },
    {
      "subject": "Uber - Request a ride",
      "licence": "App Store artwork",
      "author": "Uber Technologies, Inc.",
      "file": null
    },
    {
      "subject": "Shazam: Find Music & Concerts",
      "licence": "App Store artwork",
      "author": "Apple",
      "file": null
    },
    {
      "subject": "Headspace: Sleep & Meditation",
      "licence": "App Store artwork",
      "author": "Headspace Inc.",
      "file": null
    }
  ],
  "show": [
    {
      "subject": "Television set",
      "licence": "CC BY-SA 2.0",
      "author": "Klaus Nahr from Germany",
      "file": "File:Museum_für_Kommunikation_-_Depot_Heusenstamm_-_Technik_12_-_Flickr_-_KlausNahr.jpg"
    }
  ]
};
